---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-dataquery
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 2999
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - {{ingress}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
    - name: TMP_DIR
      value: /tmp
    - name: APP_ORIGIN
      value: {{APP_ORIGIN}}
    - name: XP_ORIGIN
      value: https://{{xpHost}}
  envFrom:
    - secret: {{secret}}
  accessPolicy:
    outbound:
      external:
        - host: {{xpHost}}
  replicas:
    min: 1
    max: 1
  resources:
  {{#with resources}}
    limits:
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  {{/with}}
