---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-dataquery
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 2999
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - {{ingress}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
    - name: TMP_DIR
      value: /tmp
  {{#each env}}
    - name: {{this.name}}
      value: {{this.value}}
  {{/each}}
  envFrom:
    - secret: {{secret}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: '4'
      memory: 3000Mi
    requests:
      cpu: '2'
      memory: 2000Mi
