name: Build and push image
description: Build app and push Docker image to NAIS

inputs:
  team:
    description: NAIS team
    required: true
  project_id:
    description: NAIS management project id
    required: true
  identity_provider:
    description: NAIS workload identity provider
    required: true

outputs:
  image:
    description: Built image reference
    value: ${{ steps.docker-push.outputs.image }}

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Login to nais registry
      uses: nais/login@v0
      with:
        team: navno

    - name: Setup node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci --ignore-scripts

    - name: Build application
      shell: bash
      run: npm run build

    - name: Prune dependencies
      shell: bash
      run: npm prune --omit=dev

    - name: Build and push Docker image
      id: docker-push
      uses: nais/docker-build-push@v0
      with:
        team: ${{ inputs.team }}
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}