name: Build and push image
description: Build app and push Docker image to NAIS

inputs:
  team:
    description: NAIS team
    required: true
  project_id:
    description: NAIS management project id
    required: true
  identity_provider:
    description: NAIS workload identity provider
    required: true

outputs:
  image:
    description: Built image reference
    value: ${{ steps.docker-push.outputs.image }}

runs:
  using: composite
  steps:
    - name: Login to nais registry
      uses: nais/login@v0
      with:
        team: ${{ inputs.team }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build application
      shell: bash
      run: pnpm run build

    - name: Delete node_modules to avoid copying them into the docker image
      shell: bash
      run: rm -rf node_modules

    - name: Install production dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prod

    - name: Build and push Docker image
      id: docker-push
      uses: nais/docker-build-push@v0
      with:
        team: ${{ inputs.team }}
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}