name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Deploy to environment'
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  build-and-deploy:
    name: Build and deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: personbruker
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          image_suffix: ${{ github.event.inputs.environment }}
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ github.event.inputs.environment }}-gcp
          RESOURCE: .nais/config.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
          VARS: .nais/vars-${{ github.event.inputs.environment }}.yml
