name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Deploy to environment'
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  build-and-deploy:
    name: Build docker image and deploy to nais k8s (${{ github.event.inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      image: ghcr.io/${{ github.repository }}:deploy-${{ github.event.inputs.environment }}-${{ github.sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: |
          docker build -t ${{ env.image }} .
          docker push ${{ env.image }}
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: ${{ github.event.inputs.environment }}-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config.yml
          VAR: image=${{ env.image }}
          VARS: .nais/vars-${{ github.event.inputs.environment }}.yml
